/* --------------------------------------------------------------------
                         Print Dialog Header File
                              Chapter 11

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define QUEUE_INFO_DLG              35
#define SELECT_PRINTER_DLG          36
#define PRINT_DLG                   37
#define PRINT_STATUS_DLG            38
#define STATUS_WND                  39

#define DID_QUEUE_NAMES             40
#define DID_PRIORITY                41
#define DID_STATUS                  42
#define DID_NUMBER_JOBS             43
#define DID_START_TIME              44
#define DID_END_TIME                45
#define DID_DEFAULT_DEVICE          46
#define DID_PRINTERS                47
#define DID_TECHNOLOGY              48
#define DID_FORMS                   49
#define DID_FORM_CX                 50
#define DID_FORM_CY                 51
#define DID_LEFT_CLIP               52
#define DID_BOTTOM_CLIP            53
#define DID_FORM_ATTR               54
#define DID_RIGHT_CLIP              55
#define DID_TOP_CLIP                56
#define DID_CAPS_WIDTH              57
#define DID_CAPS_HEIGHT             58
#define DID_HORZ_RES                59
#define DID_VERT_RES                60
#define DID_BITBLT                  61
#define DID_BANDING                 62
#define DID_SETPEL                  63
#define DID_RASTER_FONT             64
#define DID_KERNING                 65
#define DID_PALETTE                 66
#define DID_JOBPROPS                67
#define DID_UPDATE                  68
#define DID_PRINTER                 69
#define DID_DOCUMENT                70
#define DID_COPIES                  71
#define DID_JOB_LIST                72
#define DID_JOBNAME                 73
#define DID_QUEUE_NAME              74
