////////////////////////////////////////////////
//RESOURCE.H
//Resource identifiers
//
//Created:	01/22/1995	Bruce Shankle

//Main resource identifier for icon and menus
#define ID_RESOURCE                     500

//MENU command identifiers
#define IDM_FILE                            600
#define IDM_EXIT                            601
#define IDM_SAVE                            602
#define IDM_SAVEAS                         603
#define IDM_SAVEANDEXIT                   604
#define IDM_OPEN                            605
#define IDM_NEW                             606
#define IDM_HELP                            607
#define IDM_ABOUT                          608
#define IDM_EDIT				609
#define IDM_CUT				610
#define IDM_COPY				611
#define IDM_PASTE				612
#define IDM_DELETE				613
#define IDM_UNDO				614
#define IDM_FIND				615
#define IDM_FINDNEXT                       616
#define IDM_REPLACE                        617
#define IDM_SETTINGS                        618
#define IDM_TABSETTINGS                    619
#define IDM_SETWRAP                        620
#define IDM_STATUSBAR                      621
#define IDM_FONT                             622
#define IDM_COLOR                            623
#define IDM_SAVESETTINGS                   624
#define IDM_RECENTFILE1                     625   
#define IDM_RECENTFILE2                     626   
#define IDM_RECENTFILE3                     627   
#define IDM_RECENTFILE4                     628
#define IDM_SEP1                              629
#define IDM_SEP2                              630
#define IDM_AUTOINDENT                      631
#define IDM_AUTOSAVE                        632
#define IDM_SPAWNZED                        633
#define IDM_CASESENSITIVEFILENAMES        644
#define IDM_RECENTFILE5                    645
#define IDM_RECENTFILE6                    646
#define IDM_RECENTFILE7                    647
#define IDM_RECENTFILE8                    648
#define IDM_RECENTFILE9                    649
#define IDM_HELPINDEX                       650
#define IDM_GENERALHELP                    651
#define IDM_USINGHELP                      652
#define IDM_KEYSHELP                       653
#define IDM_HELPCONTENTS                  654
#define HELP_CLIENT              655
#define SUBHELP_CLIENT           656
#define EXTHELP_CLIENT           657
#define KEYSHELP_CLIENT          658
#define IDM_IMPORT                        659
#define IDM_REGISTRATION            660

