///////////////////////////////////////////////////////////
// RESOURCE.H
// Resource header file for ZIN installation program.
//
// History:
//    Created:    04/09/95    1.0    Bruce Shankle
///////////////////////////////////////////////////////////

#define ID_RESOURCE 500

//Get dir dialog
#define TXT_DIR                     501
#define IDB_DIR_OK                  502
#define IDB_DIR_CANCEL              503
#define IDD_GETDIR                  504

//README dialog
#define IDD_README    505
#define ID_RM_MLE       506
#define IDB_RM_IUNDERSTAND 507
#define IDB_RM_CANCELINSTALL 508

//String table id's
#define ID_APPNAME     1000
#define ID_FIRSTMSG    1001
#define ID_DEFAULTDIR 1002
#define ID_CANCELINSTALL 1003
#define ID_QUERYCREATEDIR 1004
#define ID_CANTCREATEDIR 1005

#define ID_ZEDEXE   1006
#define ID_ZEDHLP  1007
#define ID_ZEDICO    1008
#define ID_ZEDREADME 1009
#define ID_REGISTER 1010

#define ID_ZED_FILENAME 1011
#define ID_ZED_HELP_FILENAME 1012
#define ID_ZED_ICON_FILENAME 1013
#define ID_ZED_README_FILENAME 1014
#define ID_REGISTER_FILENAME 1015

#define ID_FILENOTFOUND 1016
#define ID_FILESNOTCOPIED 1017

#define ID_COPYZEDEXE   1018
#define ID_COPYZEDHLP  1019
#define ID_COPYZEDICO    1020
#define ID_COPYZEDREADME 1021
#define ID_COPYREGISTER 1022

#define ID_CANTCREATEOBJECT 1023

#define ID_SUCCESS 1024

#define ID_CREATINGOBJECT 1025

#define ID_PATCHFAILED 1026
#define ID_PATCHINGZED 1027

//Status dialog
#define IDD_STATUS                  3000
#define ID_TXT_STATUS              3001












